apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka-lab
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: inner
    - port: 9093
      name: controller
  selector:
    app: kafka
  clusterIP: None # Headless service for KRaft
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka-lab
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-svc.kafka-lab.svc.cluster.local:9092"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: CLUSTER_ID
              value: "L629Z6wRRE67O_bI5q3WvA"
          ports:
            - containerPort: 9092
            - containerPort: 9093
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
