apiVersion: batch/v1
kind: Job
metadata:
  name: create-topic
  namespace: kafka-lab
spec:
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: apache/kafka:3.7.0
          command:
            - /opt/kafka/bin/kafka-topics.sh
            - --create
            - --if-not-exists
            - --topic
            - kafka_lab_test_nubeprivada
            - --bootstrap-server
            - kafka-svc.kafka-lab.svc.cluster.local:9092
            - --partitions
            - "1"
            - --replication-factor
            - "1"
      restartPolicy: OnFailure
  backoffLimit: 4
