apiVersion: v1
kind: Pod
metadata:
  name: sysadmin-debugger
  namespace: kube-system
spec:
  hostPID: true
  hostNetwork: true
  containers:
    - name: debugger
      image: alpine:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      securityContext:
        privileged: true
