apiVersion: v1
kind: Pod
metadata:
  name: rescue-pod
  namespace: kube-system
spec:
  hostPID: true
  hostNetwork: true
  containers:
    - name: rescue
      image: registry.k8s.io/kube-apiserver:v1.31.1
      command: ["/bin/sh", "-c", "sleep infinity"]
      securityContext:
        privileged: true
